### ISSUE TITLE
promise based decorators?

### ISSUE THREAD

**Issue by k1r0s** [k1r0s/kaop-ts#118]
Actually decorating a method with a async decorator will cause the entire method to be unable to return a value (since we're wrapping the entire method with another function that will trigger asynchronous code)..

Basically, if you need keep track of "when the body method got executed" in order to properly separate concerns, that thing is not possible with the current solution which is callback based.

Currently is possible to execute a method wrapped with an async decorator, so the actual __method__ will be delayed till you fulfill some resource or perform that task. But you don't have any tools to realize about this __from the context that you invoke the method__.

Promises have this purpose, __they aren't just an alternative on asynchronous code, but a convention__, and maybe this library needs to take advantage of it

**Comment by k1r0s** [comment]
https://github.com/k1r0s/kaop/commit/d3c6cb2f902e0093f14e60c92858cad8ce0ac2f4

**Comment by greg-murray-volusion** [comment]
Does this mean we can now use `kaop-ts` with promises?  Should this issue then be closed?  Thanks

**Comment by k1r0s** [comment]
I made that change on kaop lib (which is a hard `kaop-ts` dependency). I have to release a minor version simply pointing to last kaop version here. 

You can try this feature now if you manually install latest kaop version on your project.

This change will make your methods wrapped with 'async' advices return a promise (or wrap existing one) in order to reflect that async process from outside of the method.

Before this change, if you had a method that returns a promise and you want to put advices on it, you couldn't properly return that promise if any of those advices contain an async task too.

I have to document that in deep, that's why this is still open :)

You can check these test in order to get more context
https://github.com/k1r0s/kaop/blob/master/test/promise-advice-method.spec.js

I can show you how this looks on es6 classes with real decorators:

this was somehow impossible with previous kaop version

```javascript
const { beforeMethod, afterMethod } = require("kaop-ts");

const delay = beforeMethod(meta => setTimeout(meta.commit, 10))
const handleError = afterMethod(meta => meta.handle())

class Dummy {

  @delay
  do1() {
    return Promise.resolve(10)
  }

  do2() {
    return Promise.resolve(10)
  }

  @delay
  do3() {
    throw new Error("lmaooo")
  }

  @delay
  @handleError
  do4() {
    throw new Error("lmaooo")
  }
}

```

**Comment by k1r0s** [comment]
keep in mind that you still rely on `meta.commit` to __complete__ a task within each advice scope. 

This change allows decorate methods that work with promises but inside advice operations you still have the same API

**Comment by greg-murray-volusion** [comment]
Cool, thanks!
