### ISSUE TITLE
Version 4.0.0 silently changes target to es6

### ISSUE THREAD

**Issue by DavideCanton** [k1r0s/kaop-ts#145]
Hi,

I didn't read in any release note of the version 4.0.0 that the target in the tsconfig was changed to es6, and this broke my angular application on IE11.

Is it necessary to compile to es6 or it could be set to es5 again?

If it isn't possible, I will fix the library version before 4.0.0

**Comment by fat23cat** [comment]
Hi,

target: es6 in the tsconfig also broke my angular application on IE11. 
Is it necessary to compile to es6 or it could be set to es5 again?

**Comment by k1r0s** [comment]
This was a fix due to a problem with babel that made classes to loose its prototype chain when using a decorator. I guess you can recompile ur bundles to es5 in order to fix IE11

**Comment by k1r0s** [comment]
if u have additional questions please reopen this issue
