### ISSUE TITLE
Result of advise's first execution repeating itself in following executions when running all tests

### ISSUE THREAD

**Issue by w-etc** [k1r0s/kaop-ts#155]
**Background**

We have an advise that takes care of checking all parameters in a request body before proceeding with the request handler's execution. If there are missing parameters, the advise returns a 400 response. If not, the advise lets the rest of the code run. The advise is the following:

```ts
export const checkParam = (properties: string[], message: string) => beforeMethod(async (meta) => {
  const event = meta.args[0]
  let body
  try {
    body = checkAndParseBody(event)
  } catch (e) {
    body = null
  }
  const decodedAuthToken = await extractAuthHeaderVerifyAndDecodeToken(event)
  const params = Object.assign({}, event.pathParameters, event.queryStringParameters, body)
  if (!params || !checkExistingProperties(params, properties)) {
    meta.prevent()
    meta.result = await getCredentialedResponse(400, {message}, getRequestOrigin(event), decodedAuthToken)
  } else {
    event.params = params
  }
  meta.commit()
})
```

We also have tests that run the request handler function and check for various response codes. The first test checks for a 200, and the next one checks for a 400.

**Problem**

When running the tests individually they both pass, but running the suite as a whole causes an error in which the second test fails. Instead of receiving a 400 response, it receives a 200 response instead. It's like the first advise's result is "recorded" and used in the following executions.

I also swapped the tests and put the 400 one first and the 200 one second. The second test failed and received a 400 instead of a 200.

**Comment by k1r0s** [comment]
Hey! which kaop-ts version are you running on your project?

**Comment by w-etc** [comment]
Version `4.0.0`

Edit: Just checked with version `4.3.0`. Error is still happening

Edit 2: I thought I'd exhausted all possibilities on my end, but after a nap I found out that the problem was in the tests setup and had nothing to do with the advises. Everything is working as expected now. Thanks for answering earlier and sorry for the false issue!

**Comment by k1r0s** [comment]
My two cents on your code: try to separate concerns as your advice is doing too much stuff alone!

You can create an advice for every phase on your pre-request stuff

checkAndParseBody
extractAuthHeaderVerifyAndDecodeToken
checkExistingProperties
getCredentialedResponse

any of them could be extracted as an advice 

This article explains for instance, how to separate concerns in backend development using advices: https://dev.to/k1r0s/idiomatic-javascript-backend-part-1-4g0b

**Comment by w-etc** [comment]
Oh, thanks for the info!
