### ISSUE TITLE
Advices on functions defined as properties

### ISSUE THREAD

**Issue by 000407** [k1r0s/kaop-ts#171]
I have the following simple advice.

```ts
const ExecuteTimed = afterMethod((meta: Metadata<OrdersController>): void => {
  console.log("Meta: ", meta);
});
```

I would like to apply the above, on a static function assigned to a **static property** of a class like follows.

```ts
class Foo {
  @ExecuteTimed
  public static test = (): void => {
    console.log("test method invoked");
  }
}
```

But I am getting the following error.
![image](https://user-images.githubusercontent.com/21293445/198195237-be5673ab-46a2-4c50-a04b-f1e1d099af28.png)

Couldn't find anything specific to this scenario in the documents either.

**Comment by k1r0s** [comment]
Hello @000407, thx for your question

These decorators can't be applied to anonymous functions. It can only be applied to methods or constructors.

**Comment by 000407** [comment]
@k1r0s That makes sense. Thanks for the feed...
