### ISSUE TITLE
discourage use of arrow functions advice declaration

### ISSUE THREAD

**Issue by k1r0s** [k1r0s/kaop-ts#18]
Join points spect a callback as a first argument

```typescript
@afterMethod(() => {
  // stuff
  this.next()
})
``` 

Problem is, most of transpilers seeing that beautiful lamda function will understand that: `THIS` NEED TO BE KEEPED! 

```javascript
var _this = this // <- WTF
@afterMethod(function() {
  // stuff
  _this.next()

})
``` 
![image](https://user-images.githubusercontent.com/6052309/29047827-efa7dec0-7bcd-11e7-8593-0f639dc3d29b.png)

kaop-ts already provides this at callback advices so if you write an arrow funciton at advice declaration transpilers will cheat you :(

always try to use function keyword during advice initialization until I find a better solution: 

```typescript
@afterMethod(function() {
  // stuff
  this.next()
})
``` 

once context is declared.. I mean, advice is properly declared using a `function` you are free to use arrow functions **inside advice function body** ;)

**Comment by jcjolley** [comment]
Is this closed b/c we can now use arrow functions instead of function, or because this problem doesn't have a work around and isn't worth the time to figure it out?

**Comment by k1r0s** [comment]
hi @jcjolley, this is closed because this issue is for documentation purpose. This problem doesn't have a workarround because when I wrote this lib I decided to put some methods on the advice context. It was not a good decision..

You have to care about lamdas when using advices that use those methods like: 

```javascript
@beforeInstance(function() {
  this.next()
  // triggers the next advice or method in the
  // call stack (mandatory if your advice contains async operations)
  this.stop() // prevent execution of decorated method (GUESS WHY)
  this.break() // prevent execution of following advices until method execution
  this.stopped // boolean, will evaluate to true if stop() was called
})
``` 

Yet inside the advice you can use arrow functions **but you have to keep the advice function as a anonymous function without a fat arrow**: 
```javascript
@beforeInstance(function() {
  someService().then(() => this.next())
})
``` 

I know this is tricky :( 

Remove `this` from kaop API is on my todo list

**Comment by k1r0s** [comment]
Here it is: https://github.com/k1r0s/kaop-ts/issues/19

**Comment by jcjolley** [comment]
@k1r0s Thanks for the speedy response!  This is an excellent lib.
