### ISSUE TITLE
[Feature Request] Add @afterException joinPoint

### ISSUE THREAD

**Issue by alexjoverm** [k1r0s/kaop-ts#2]
It'd be nice to have this JoinPoint given by the library. Currently it's possible to do that by custom implementation:

```typescript
static onException () {
  try {
    meta.result = meta.rawMethod.apply(meta.scope, meta.args)
  } catch(e){
    // stuff
  }
}
```

Although it would be much convenient to have this join point to save some code lines :)

**Comment by k1r0s** [comment]
Hi @alexjoverm, thanks for the idea.

This library focus on provide flat options to build more complex stuff.

Now, if you want to handle exceptions in decorated method you can place `onException` to be invoked just before (last before) **to prevent main method execution** using `this.stop`. So, as you suggested, the method is wrapped with `try, catch`.

```Javascript
  this.stop()
  try {
    meta.result = meta.fakeReplacement.$$raw.apply(meta.scope, meta.args)
  } catch (err) {
    // stuff
  }

```
I'll try to give a standard solution.

**Comment by k1r0s** [comment]
This is what implementation would look like

This feature should pass this test: 

```Javascript
import { AdvicePool, IMetadata, onException, adviceMetadata } from "../../src/kaop-ts"

class MyAdvicePool extends AdvicePool {
  static handleError (@adviceMetadata meta: IMetadata) {
    console.log(`There was an error in ${meta.propertyKey}(): -> ${meta.err.message}`)
  }
}

class ExceptionTest {

  @onException(MyAdvicePool.handleError)
  // static wrongMethod (callback: number | Function) {
  static wrongMethod (callback: any) {
    callback()
  }
}

describe("kaop-ts demo -> exception join point", () => {
  it("advice should be executed when decorated method throws an exception", (done) => {
    ExceptionTest.wrongMethod(2)
    ExceptionTest.wrongMethod(done)
  })
})

``` 

Check the difference between the previous test
