### ISSUE TITLE
Why AdvicePool, adviceMetadata, IMetadata is not imported from kaop-ts?

### ISSUE THREAD

**Issue by kailashthakuri** [k1r0s/kaop-ts#89]
![kaop](https://user-images.githubusercontent.com/17194118/38796304-c0f82ada-417a-11e8-929a-dab534cebb14.PNG)

I have installed kaop-ts. Is there any other dependencies or package i have to install along with kaop-ts?

**Comment by k1r0s** [comment]
Thanks @kailashthakuri 

You're using an outdated API, please refer to the docs https://github.com/k1r0s/kaop-ts/blob/master/docs/api.md#how-do-i-define-an-advice

You no longer need to import AdvicePool, adviceMetadata, etc

May I know where did you find that code snipped? need to update it

**Comment by k1r0s** [comment]
@kailashthakuri try this code snippet

```javascript
const { beforeMethod } = require(".");

const yourAdvice = meta => {
  console.log(meta.target)
  console.log(meta.args)
}

class YourService {
  @beforeMethod(yourAdvice)
  static someMethod(num, str) {

  }
}

YourService.someMethod(1, "asdasd");
```

**Comment by kailashthakuri** [comment]
Thanks, But I just want to track which component and method get called for event tracking. I don't want to send parameter to my advice. i am trying to implement AOP in angular5. I want to intercept the method called and keep log for event tracking purpose.

**Comment by k1r0s** [comment]
mmm okay, 

try this out:

```javascript
const { beforeMethod } = require("kaop-ts");

const Log = meta => {
  console.log(meta.key)
  console.log(meta.scope)
  console.log(meta.args)
}

function applyToAll(advice) {
  return function applyAll(target) {
    const wove = beforeMethod(advice);
    for (let key in target.prototype) {
      Object.defineProperty(target.prototype, key,
        wove(target, key, Object.getOwnPropertyDescriptor(target.prototype, key)));
    }
  }

}

const track = applyToAll(Log)

@track
class YourService {
  method1(num, str) {

  }
  method2(num, str) {

  }
  method3(num, str) {

  }
  method4(num, str) {

  }
}

const b = new YourService;
const a = new YourService;

b.method1(1, 123)
a.method2("asdas", 131231)
a.method4({asd: 1}, 131231)

```

**Comment by kailashthakuri** [comment]
Thanks a lot.  
Here. I am using using annotation in method level.

export class SigninComponent implements OnInit {
  constructor(private store: Store<fromApp.AppState>, private eventTrackingService: EventTrackingService) { }
  ngOnInit() {
  }
  @log()
  submitForm(form: NgForm) {
    let userName = form.value.userName;
    let password = form.value.password;
    this.store.dispatch(new AuthActions.trySignin({ username: userName, password: password }));
  }
}

log.service.ts
import {  beforeMethod } from "kaop-ts";

export const log = () => beforeMethod(meta => {
 console.log("Method Name : "+ meta.key);
 console.log("Class : "+  meta.target);
})

Here how can i get component Name? meta.target is not returning component name.

**Comment by k1r0s** [comment]
`console.log(meta.target.name)` should do the trick

https://github.com/k1r0s/kaop-ts/blob/master/docs/api.md#metadata

as pointed in the docs:   

```
meta.target // Class definition
```

@kailashthakuri  going to close this since questions are out of issue's scope. 

Thanks!
